#!/usr/bin/env python
from socket import socket, AF_INET, SOCK_STREAM
import select

if __name__ == '__main__':
    proxyName = 'localhost'
    proxyPort = 11000
    clientSocket = socket(AF_INET, SOCK_STREAM)
    clientSocket.connect((proxyName,proxyPort))
    sentence = raw_input('Input sentence: ')
    clientSocket.send(sentence)
    modifiedSentence = clientSocket.recv(8192)
    print ('From Server: ' +  modifiedSentence)
    clientSocket.close()
